-- Insert 60 Symptoms records
INSERT INTO Symptoms (symptom_id, disease_id, symptom_description, severity_level)
VALUES
    ('S100', 'D100', 'Fever, chills, body aches', 'Moderate'),
    ('S101', 'D101', 'Cough, shortness of breath, fever', 'Severe'),
    ('S102', 'D102', 'Fever, sweating, chills, fatigue', 'Severe'),
    ('S103', 'D103', 'Persistent cough, chest pain, blood in sputum', 'Severe'),
    ('S104', 'D104', 'Fatigue, loss of appetite, jaundice', 'Moderate'),
    ('S105', 'D105', 'High fever, runny nose, sore throat, rash', 'Severe'),
    ('S106', 'D106', 'Itchy rash, red spots, flu-like symptoms', 'Moderate'),
    ('S107', 'D107', 'Fever, rash, muscle pain, fatigue', 'Severe'),
    ('S108', 'D108', 'Cough, shortness of breath, chest pain', 'Severe'),
    ('S109', 'D109', 'Fever, night sweats, weight loss', 'Severe'),
    ('S110', 'D110', 'Fever, headache, rash, joint pain', 'Moderate'),
    ('S111', 'D111', 'Rash, fever, fatigue, muscle pain', 'Severe'),
    ('S112', 'D112', 'Jaundice, abdominal pain, dark urine', 'Moderate'),
    ('S113', 'D113', 'Severe headache, stiff neck, nausea', 'Severe'),
    ('S114', 'D114', 'Fever, headache, weakness', 'Severe'),
    ('S115', 'D115', 'Muscle spasms, jaw stiffness, trouble swallowing', 'Severe'),
    ('S116', 'D116', 'Fever, fatigue, weakness, headache', 'Severe'),
    ('S117', 'D117', 'Jaundice, abdominal pain, fever', 'Severe'),
    ('S118', 'D118', 'Fever, muscle aches, cough, difficulty breathing', 'Moderate'),
    ('S119', 'D100', 'Fatigue, body aches, chills, headache', 'Moderate'),
    ('S120', 'D101', 'Shortness of breath, fever, body aches', 'Severe'),
    ('S121', 'D102', 'Chills, fever, body aches, fatigue', 'Moderate'),
    ('S122', 'D103', 'Chronic cough, fatigue, chest pain', 'Severe'),
    ('S123', 'D104', 'Loss of appetite, nausea, fatigue', 'Moderate'),
    ('S124', 'D105', 'Sore throat, fever, red rash, body aches', 'Severe'),
    ('S125', 'D106', 'Itchy red rash, fever, sore throat', 'Moderate'),
    ('S126', 'D107', 'High fever, rash, joint pain, muscle pain', 'Severe'),
    ('S127', 'D108', 'Chest pain, difficulty breathing, coughing up blood', 'Severe'),
    ('S128', 'D109', 'Night sweats, fatigue, weight loss, fever', 'Severe'),
    ('S129', 'D110', 'Fever, rash, joint pain, headache', 'Moderate'),
    ('S130', 'D111', 'Fatigue, fever, sore throat, headache', 'Severe'),
    ('S131', 'D112', 'Jaundice, abdominal pain, nausea, fatigue', 'Moderate'),
    ('S132', 'D113', 'Headache, stiff neck, fever, sensitivity to light', 'Severe'),
    ('S133', 'D114', 'Nausea, vomiting, headache, fatigue', 'Moderate'),
    ('S134', 'D115', 'Severe muscle pain, jaw stiffness, difficulty swallowing', 'Severe'),
    ('S135', 'D116', 'Tiredness, fever, headache, back pain', 'Moderate'),
    ('S136', 'D117', 'Severe fatigue, dark urine, jaundice', 'Severe'),
    ('S137', 'D118', 'Fever, headache, nausea, fatigue', 'Moderate'),
    ('S138', 'D100', 'Cough, sore throat, body aches, fever', 'Mild'),
    ('S139', 'D101', 'Fatigue, muscle pain, chills, cough', 'Moderate'),
    ('S140', 'D102', 'Fever, chills, headache, nausea', 'Moderate'),
    ('S141', 'D103', 'Cough, chest tightness, blood-tinged sputum', 'Severe'),
    ('S142', 'D104', 'Abdominal pain, loss of appetite, yellowing of skin', 'Moderate'),
    ('S143', 'D105', 'Fever, sore throat, fatigue, skin rash', 'Severe'),
    ('S144', 'D106', 'Rash, fatigue, fever, sore throat', 'Moderate'),
    ('S145', 'D107', 'Joint pain, muscle aches, fever, rash', 'Severe'),
    ('S146', 'D108', 'Cough, shortness of breath, fatigue', 'Moderate'),
    ('S147', 'D109', 'Fatigue, night sweats, weight loss, fever', 'Severe'),
    ('S148', 'D110', 'Fever, headache, rash, joint pain', 'Moderate'),
    ('S149', 'D111', 'Fatigue, fever, sore throat, red rash', 'Severe'),
    ('S150', 'D112', 'Fatigue, jaundice, abdominal pain, fever', 'Moderate'),
    ('S151', 'D113', 'Headache, stiff neck, fever, nausea', 'Severe'),
    ('S152', 'D114', 'Headache, fatigue, muscle aches, fever', 'Moderate'),
    ('S153', 'D115', 'Muscle stiffness, fever, trouble swallowing', 'Severe'),
    ('S154', 'D116', 'Tiredness, fever, body aches, headache', 'Moderate'),
    ('S155', 'D117', 'Jaundice, nausea, fatigue, abdominal pain', 'Severe'),
    ('S156', 'D118', 'Cough, fever, muscle pain, difficulty breathing', 'Moderate'),
    ('S157', 'D100', 'Chills, cough, headache, body aches', 'Mild'),
    ('S158', 'D101', 'Cough, fever, fatigue, shortness of breath', 'Severe'),
    ('S159', 'D102', 'Sweating, chills, fever, fatigue', 'Moderate'),
    ('S160', 'D103', 'Fatigue, chest pain, coughing blood', 'Severe');
